version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-ajay-asset
    ports:
      - "6628:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: asset_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend-ajay-asset
    ports:
      - "3069:3069"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: asset_management
      DB_PASSWORD: admin123
      DB_PORT: 5432

  frontend:
    build: ./Frontend
    container_name: frontend-ajay-asset
    ports:
      - "8194:80"
    depends_on:
      - backend

  hrpage:
    build: ./Hr_Page
    container_name: hrpage-ajay-asset
    ports:
      - "8195:80"
    depends_on:
      - backend

volumes:
  postgres_data:

